version: "3.5"
services:
  app-nginx:
    image: nginx
    build:
      context: ../
      dockerfile: ./nginx/Dockerfile
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"